version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=your_openai_api_key_here
